Watching for file changes with StatReloader
[13/May/2021 00:23:17] "GET / HTTP/1.1" 200 15745
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 00:23:18] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 00:23:18] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 00:23:18] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
[13/May/2021 00:23:50] "GET / HTTP/1.1" 200 15745
[13/May/2021 00:30:05] "GET / HTTP/1.1" 200 15745
Not Found: /assets/js/vendor/popper.min.js
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 00:30:06] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
[13/May/2021 00:30:06] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 00:30:06] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 00:30:07] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 00:30:07] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 00:30:08] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 00:30:08] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 00:43:29] "GET / HTTP/1.1" 200 15745
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 00:43:34] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 00:43:34] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 00:43:34] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 00:43:47] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 00:43:48] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 00:43:51] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 00:44:08] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 00:45:19] "GET / HTTP/1.1" 200 15745
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 00:45:19] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 00:45:19] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 00:45:19] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 00:45:20] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 00:45:21] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
/home/ubuntu/streaming/streaming/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
May 13, 2021 - 00:23:02
Django version 3.2.2, using settings 'streaming.settings'
Starting development server at http://51.195.91.98:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Traceback (most recent call last):
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 68, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/streaming/env/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/streaming/streaming/settings.py", line 14, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
Watching for file changes with StatReloader
[13/May/2021 03:09:31] "GET / HTTP/1.1" 200 16108
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 03:09:32] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 03:09:32] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 03:09:32] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 03:09:38] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 05:14:23] code 400, message Bad request version ('À\x14À')
[13/May/2021 05:14:23] You're accessing the development server over HTTPS, but it only supports HTTP.

[13/May/2021 07:22:12] "GET / HTTP/1.1" 200 16108
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 07:22:13] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 07:22:13] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 07:22:13] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 07:22:15] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 07:24:20] "GET / HTTP/1.1" 200 16108
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 07:24:21] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 07:24:21] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 07:24:21] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 07:24:22] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 07:24:23] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 07:24:23] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 07:24:25] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 07:25:25] "GET / HTTP/1.1" 200 16108
[13/May/2021 11:18:38] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
[13/May/2021 11:18:38] "  /*à     Cookie: mstshash=Administr" 400 -
[13/May/2021 12:36:20] code 400, message Bad request version ('©SmÐ\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
[13/May/2021 12:36:20] You're accessing the development server over HTTPS, but it only supports HTTP.

[13/May/2021 12:36:20] code 400, message Bad request version ('&$×}\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
[13/May/2021 12:36:20] You're accessing the development server over HTTPS, but it only supports HTTP.

[13/May/2021 12:36:30] code 400, message Bad request version ('\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
[13/May/2021 12:36:30] You're accessing the development server over HTTPS, but it only supports HTTP.

[13/May/2021 12:36:30] code 400, message Bad request version ('hÝBå\x818±½\x00$\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
[13/May/2021 12:36:30] You're accessing the development server over HTTPS, but it only supports HTTP.

[13/May/2021 14:38:03] "GET / HTTP/1.1" 200 12687
Not Found: /assets/js/vendor/popper.min.js
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 14:38:04] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
[13/May/2021 14:38:04] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 14:38:04] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 14:38:05] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 14:38:05] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 14:38:06] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 14:38:06] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 14:38:14] "GET / HTTP/1.1" 200 12687
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 14:38:14] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 14:38:14] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 14:38:14] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
[13/May/2021 16:01:05] "GET / HTTP/1.1" 200 12687
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 16:01:07] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 16:01:07] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 16:01:07] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 16:01:12] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 16:43:49] "GET / HTTP/1.1" 200 12687
[13/May/2021 16:43:49,568] - Broken pipe from ('74.82.47.2', 45884)

[13/May/2021 16:48:59] code 400, message Bad HTTP/0.9 request type ('\x00\x00\x00')
[13/May/2021 16:48:59] "    c                           " 400 -
[13/May/2021 19:26:34] "GET / HTTP/1.1" 200 12687
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:26:35] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:26:35] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:26:36] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:26:36] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:26:36] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
[13/May/2021 19:27:23] "GET / HTTP/1.1" 200 12687
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:27:23] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:27:23] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:27:23] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
[13/May/2021 19:33:50] "GET / HTTP/1.1" 200 12687
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:33:51] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:33:51] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:33:51] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:33:52] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:33:52] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 19:33:54] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 19:33:56] "GET / HTTP/1.1" 200 12687
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:33:56] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:33:56] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:33:57] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
[13/May/2021 19:40:13] "GET / HTTP/1.1" 200 13054
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:40:14] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:40:14] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:40:14] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:40:14] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:40:15] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:40:15] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /favicon.ico
[13/May/2021 19:40:16] "GET /favicon.ico HTTP/1.1" 404 2216
Not Found: /spelunky.gif
[13/May/2021 19:40:18] "GET /spelunky.gif HTTP/1.1" 404 2219
[13/May/2021 19:41:15] "GET / HTTP/1.1" 200 13054
Not Found: /spelunky.gif
[13/May/2021 19:41:42] "GET /spelunky.gif HTTP/1.1" 404 2219
[13/May/2021 19:42:15] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:42:16] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:42:16] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:42:17] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:42:17] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
[13/May/2021 19:42:17,330] - Broken pipe from ('186.95.24.164', 49053)

Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:42:17] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:42:18] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[13/May/2021 19:42:19] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /spelunky.gif
[13/May/2021 19:42:29] "GET /spelunky.gif HTTP/1.1" 404 2219
[13/May/2021 19:42:35] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:42:35] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:42:36] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:42:36] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
[13/May/2021 19:42:36,394] - Broken pipe from ('186.95.24.164', 49124)

Not Found: /spelunky.gif
[13/May/2021 19:42:36] "GET /spelunky.gif HTTP/1.1" 404 2219
[13/May/2021 19:42:52] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:42:52] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:42:53] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:42:53] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:42:53] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:42:54] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:42:54] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[13/May/2021 19:42:55] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /favicon.ico
[13/May/2021 19:43:09] "GET /favicon.ico HTTP/1.1" 404 2216
Not Found: /spelunky.gif
[13/May/2021 19:43:26] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /spelunky.gif
[13/May/2021 19:43:27] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /favicon.ico
[13/May/2021 19:43:27] "GET /favicon.ico HTTP/1.1" 404 2216
Not Found: /spelunky.gif
[13/May/2021 19:45:42] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /spelunky.gif
[13/May/2021 19:45:51] "GET /spelunky.gif HTTP/1.1" 404 2219
[13/May/2021 19:49:30] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:49:30] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:49:30] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:49:30] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 19:49:31] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 19:49:31] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 19:49:32] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[13/May/2021 19:49:33] "GET /spelunky.gif HTTP/1.1" 404 2219
[13/May/2021 20:14:40] "GET / HTTP/1.1" 200 13054
[13/May/2021 22:44:35,449] - Broken pipe from ('74.120.14.40', 46578)

[13/May/2021 22:44:36] "GET / HTTP/1.1" 200 13054
[13/May/2021 22:44:36,663] - Broken pipe from ('74.120.14.40', 51098)

[13/May/2021 22:44:36] "GET / HTTP/1.1" 200 13054
[13/May/2021 23:01:14] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 23:01:14] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 23:01:14] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 23:01:14] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 23:01:16] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 23:01:16] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 23:01:16] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 23:01:17] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 23:01:17] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 23:01:18] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[13/May/2021 23:01:19] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /favicon.ico
[13/May/2021 23:01:55] "GET /favicon.ico HTTP/1.1" 404 2216
[13/May/2021 23:02:40] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[13/May/2021 23:02:40] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[13/May/2021 23:02:40] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[13/May/2021 23:02:40] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[13/May/2021 23:02:41] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /favicon.ico
[13/May/2021 23:03:19] "GET /favicon.ico HTTP/1.1" 404 2216
[14/May/2021 00:54:26] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 00:54:26] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 00:54:26] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 00:54:27] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 00:54:28] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 00:54:28] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 00:54:29] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 00:54:36] "GET /spelunky.gif HTTP/1.1" 404 2219
[14/May/2021 01:05:16] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:05:17] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:05:17] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:05:17] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:05:20] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:05:20] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:05:22] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:05:23] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /spelunky.gif
[14/May/2021 01:05:29] "GET /spelunky.gif HTTP/1.1" 404 2219
[14/May/2021 01:14:15] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:14:16] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:14:16] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:14:16] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:14:16] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:14:17] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:14:17] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:14:17] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:14:18] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:14:18] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:14:19] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /favicon.ico
[14/May/2021 01:14:22] "GET /favicon.ico HTTP/1.1" 404 2216
[14/May/2021 01:18:28] "GET / HTTP/1.1" 200 13054
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:18:29] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:18:29] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:18:30] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:18:35] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:18:36] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:18:36] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:18:39] "GET /spelunky.gif HTTP/1.1" 404 2219
[14/May/2021 01:19:30] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:19:31] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:19:31] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:19:31] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:19:33] "GET /spelunky.gif HTTP/1.1" 404 2219
[14/May/2021 01:24:09,350] - Broken pipe from ('162.142.125.39', 46298)

[14/May/2021 01:24:10] "GET / HTTP/1.1" 200 13054
[14/May/2021 01:24:10,575] - Broken pipe from ('162.142.125.39', 46892)

[14/May/2021 01:24:10] "GET / HTTP/1.1" 200 13054
[14/May/2021 01:25:30] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:25:31] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:25:31] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:25:31] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:25:32] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:25:32] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:25:32] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:25:33] "GET /spelunky.gif HTTP/1.1" 404 2219
[14/May/2021 01:28:16] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:28:16] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:28:16] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:28:17] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:28:17] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:28:18] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:28:18] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:28:20] "GET /spelunky.gif HTTP/1.1" 404 2219
[14/May/2021 01:29:29] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:29:30] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
[14/May/2021 01:29:30] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:29:30] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:29:31] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /favicon.ico
[14/May/2021 01:29:35] "GET /favicon.ico HTTP/1.1" 404 2216
[14/May/2021 01:31:03] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:31:03] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:31:04] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:31:04] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:31:04] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:31:05] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:31:05] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:31:06] "GET /spelunky.gif HTTP/1.1" 404 2219
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:34:08] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:34:08] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /spelunky.gif
[14/May/2021 01:34:17] "GET /spelunky.gif HTTP/1.1" 404 2219
[14/May/2021 01:34:51] "GET / HTTP/1.1" 200 13054
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:34:52] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:34:52] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:34:52] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /assets/js/vendor/popper.min.js
[14/May/2021 01:34:53] "GET /assets/js/vendor/popper.min.js HTTP/1.1" 404 2273
Not Found: /dist/js/bootstrap.min.js
[14/May/2021 01:34:53] "GET /dist/js/bootstrap.min.js HTTP/1.1" 404 2255
Not Found: /assets/js/vendor/holder.min.js
[14/May/2021 01:34:53] "GET /assets/js/vendor/holder.min.js HTTP/1.1" 404 2273
Not Found: /spelunky.gif
[14/May/2021 01:34:54] "GET /spelunky.gif HTTP/1.1" 404 2219
